---
title: 'Assignment 7: Stability'
author: "Katheryn Moya and Sarah Lam"
date: "2023-06-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sensitivity)
library(tidyverse)
library(deSolve)
library(ggpubr)
```


## Build Harvest Model 
```{r}

source("~/Documents/MESM Year 2/ESM232/esm232_a7/R/dpredpreyharvest.R")

dpredpreyharvest

```


## Run Model for 200 years 

Start with initial condition of 1 prey and 1 predator, rprey=0.95, alpha=0.01, eff=0.6,pmort=0.4, K=2000.

```{r}
# set initial population size 

initialpop = c(prey = 1, pred = 1)

# come up with first set of parameters

rprey = 0.95
alpha = 0.01
eff = 0.6
pmort = 0.4
K = 2000
thresh = 0.7
harv = 0.1

#convert to a dataframe
pars <- cbind.data.frame(rprey, alpha, eff, pmort, K, thresh, harv)

# gets results for 200 years (evaluating every year)
years <-seq(from=1, to= 200)

# run model for 50 years using ODE solver

results <- ode(y = initialpop, times = years, func= dpredpreyharvest, parms = parms)
head(results)

# extract results
res = as.data.frame(results) %>% gather(key="animal", value="pop",-time)

ggplot(as.data.frame(res), aes(time, pop , col=animal))+geom_line()
```


## Sensitivity analysis of different hunting levels and minimum prey populations

We decided to define stability as maintaining the prey population above 300 after 50 years


```{r}
# set parameter list
pars = data.frame(rprey = 0.95, alpha = 0.01, eff = 0.6, pmort = 0.4, K = 200, thresh = 100, harv = 0.3)


# now lets try initial conditions that will be stable
preyi = with(pars, pmort/(eff*alpha)) 
predi = with(pars, rprey/alpha*(1-preyi/K)) 

preyi
predi

# times when you want to evaluate
years = seq(from=1,to=50)

# stable prey = 66.6
# stable pred = 63.3
```



```{r}

#use a wrapper function with pmap

#threshold list
thresh_l <- seq(from = 10, to = 150, by = 1)

#wrapper function
harvest_wrapper <- function(t, func, pop, rprey, alpha, eff, pmort, K, harv, thresh) {
    pars <- list(rprey=rprey, alpha=alpha, eff=eff, pmort=pmort, K=K, harv = harv, thresh = thresh)
    
    #run the ode solver
    result <- ode(y = pop, times = years, func = func, parms = pars, maxsteps = 500) 
  
    #turn into dataframe and get max value
    result <- as.data.frame(result)
    colnames(result) = c("time", "prey", "pred")
    final_pop <- max(result$prey)
    
    return(final_pop)
}

#use pmap to apply wrapper to all parameter sets

years <- seq(from=1, to=50)

pars = data.frame(rprey = 0.95, alpha = 0.01, eff = 0.6, pmort = 0.4, K = 200, thresh = 100, harv = 0.3)


#setting initial population values
intitalpred <- with(pars, pmort/(eff*alpha))
intialprey <- with(pars, rprey/alpha*(1-predi/K))
intitalpop <- c(prey = as.integer(preyi), pred = as.integer(predi))

all_results <- pars %>% 
  pmap(harvest_wrapper, t = years, func = dpredpreyharvest, pop = initialpop)

all_results_df <- as.data.frame(all_results)
```

### Different Levels of Hunting

```{r}
#use a wrapper function with pmap

#harvest list
harvest_l <- seq(from = 0.05, to = 0.50, by = 0.01)

#use pmap to apply wrapper to all parameter sets

years <- seq(from=1, to=50)

pars_harv_l <- list(rprey=0.95, alpha=0.01, eff=0.6, pmort=0.4, K=200, harvest = harvest_l, thresh = 66)

pars_harv_df <- as.data.frame(pars_harv_l)

#set initial population values
predi <- with(pars_harv_l, pmort/(eff*alpha))
preyi <- with(pars_harv_l, rprey/alpha*(1-predi/K))
pop <- c(prey = as.integer(preyi), pred = as.integer(predi))

results_harv <- pars_harv_df %>% 
  pmap(harvest_wrapper, t = ears, func = dpredpreyharvest, pop = pop)

all_results_df_h <- dplyr::bind_rows(results_harv, .id = "pars") %>% 
  cbind(as.data.frame(harvest_l)) %>% 
  filter(time == 50)
```

## Plot final ode run

```{r}
#selected parameters
pars_final <- list(rprey=0.95, alpha=0.01, eff=0.6, pmort=0.4, K=2000, harvest = 0.13, thresh = 61)

#set initial population values
predi <- with(pars_graph, pmort/(eff*alpha))
preyi <- with(pars_graph, rprey/alpha*(1-predi/K))
pop <- c(prey = as.integer(preyi), pred = as.integer(predi))

#run times
times <- 1:250

#run the ode
results <- ode(y = pop, times = times, func = dpredpreyharvest, parms = pars_graph, maxsteps = 500000)

plot_df <- as.data.frame(graph_result) %>% 
  pivot_longer(-time, names_to = "animal", values_to = "pop")

ggplot(plot_df, aes(time, pop, col=animal)) + 
  geom_line() + 
  labs(x = "Time (days)", 
       y = "Population")

```




